# Generated by Django 5.1.4 on 2025-01-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_certificate_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['date'], 'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
    ]
